version: '3.1'  #도커 컴포즈 버전 설정

services:
  jigu-in:  #서비스 명
    image: mysql:8.0  #사용할 이미지
    container_name: jiguin-db #컨테이너 명
    ports:
      - "9909:3306" #로컬 포트 : 컨테이너 포트
    environment:
      MYSQL_ROOT_PASSWORD: save
      TZ: Asia/Seoul
    volumes:
      - ../../database/mysql/:/var/lib/mysql #데이터 로컬 저장 폴더:컨테이너 저장 폴더

